experiment:
  name: CDiff_DiT_delta
  output_dir: saved_models/CDiff_DiT_delta
  seed: 42

runtime:
  data_dir: data/out_combined_stereo # dataset path
  gpu: 0
  amp: true
  cudnn_benchmark: true
  allow_tf32: true
  matmul_precision: high

data:
  inp_type: wav # flac may not work without modifications
  sr: 44100
  hop: 384
  win: 1024
  fft: 1024
  win_fn: hann
  center: true
  val_split: 0.2
  batch_size: 8

train:
  epochs: 200
  patience: 7
  gen_val_batch: true

  learning_rate: 1.0e-4
  beta1: 0.9
  beta2: 0.98
  eps: 1.0e-8
  weight_decay: 0.0
  ema_decay: 0.995
  grad_clip: 1.0

  optimizer:
    name: adamw
    fused: true

  lr_policy: fixed
  # for warmup cosine etc
  warmup_steps: 2000
  restart_epochs: 30
  warmup_initial_lr: 1.0e-6
  warmup_epochs: 3
  cosine_floor_factor: 1.0e-2

  diffusion_steps: 16
  diffusion_mode: linear
  alpha_mode: cos2
  residual_mode: next_delta_norm 

  loss:
    delta_weight: 0.7
    recon_weight: 0.3
    audio_weight: 8.0
    multiply_factor : 50.0 # mutiply factor for better loss calculation

model:
  backbone: dit

  in_chans: 4
  dropout: 0.0
  continuous_emb: false
  residual_prediction: true

  embed_dim: 768
  num_heads: 8
  num_layers: 5
  max_freq: 1000.0 # use if continuous_emb = True
  patch_f: 19 
  patch_t: 9 
  time_stride: 4 # set to 8 for 50% overlap in time if you want fewer artifacts. 
  pos_embed: sincos_2d # "sincos_2d" ignored when use_rope=True
  use_rope: true   # set True to enable RotaryEmbedding (1D over tokens)

  reinit_projection: true # makes encoder ~orthonormal; decoder ~pseudoinverse