experiment:
  name: CDiff_UNet_direct
  output_dir: saved_models/CDiff_UNet_direct_e
  seed: 42

runtime:
  data_dir: data/out_combined_stereo #dataset path
  gpu: 1
  amp: true
  cudnn_benchmark: true
  allow_tf32: false
  matmul_precision: high


data:
  inp_type: wav # flac may not work without modifications
  sr: 44100
  hop: 384
  win: 1024
  fft: 1024
  win_fn: hann
  center: true
  val_split: 0.2
  batch_size: 8

train:
  epochs: 200
  patience: 7 # for early stopping 
  gen_val_batch: true # for generating a random validation batch

  learning_rate: 1.0e-4
  beta1: 0.9
  beta2: 0.98
  eps: 1.0e-8
  weight_decay: 0.0
  ema_decay: 0.995
  grad_clip: 1.0

  optimizer:
    name: adam
    fused: false

  lr_policy: fixed
  # for warmup cosine etc
  warmup_steps: 2000
  restart_epochs: 30
  warmup_initial_lr: 1.0e-6
  warmup_epochs: 3
  cosine_floor_factor: 1.0e-2

  diffusion_steps: 16
  diffusion_mode: linear
  alpha_mode: cos2
  residual_mode: direct # direct spectrogram generation

  loss:
    audio_weight: 8.0
    multiply_factor : 50.0 # mutiply factor for better loss calculation

model:
  backbone: unet

  in_chans: 4
  dropout: 0.1
  continuous_emb: false
  residual_prediction: false

  num_res_blocks: 2
  use_attention: true # Bottleneck attention
  channels: 64
  ch_mult: [1, 2, 4, 8]
  use_norm: true # Usage of BN or GN layers in Residual blocks
  num_groups: 8
  resample_with_conv: true # Dowsampling with conv2d
  use_ckpt: true # enable gradient checkpointing inside backbones (VRAM saver)